#!/usr/bin/env bash
# lib/finalize.sh - Finalization and reporting

# Requires: WORK_DIR, WORKING_BRANCH, DEFAULT_BRANCH, ISSUE, REPO, ISSUE_TITLE
#           TESTS_PASSED, REVIEW_PASSED, PR_URL
# Uses: commit_changes, push_branch, create_pr, add_issue_comment, has_uncommitted_changes

finalize_success() {
    log_phase "FINALIZING - SUCCESS"
    
    commit_changes "fix: resolve issue #${ISSUE}" "${ISSUE_TITLE}

Automatically generated by issue-resolver bot."
    
    push_branch
    create_pr
    add_issue_comment "success"
    
    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║                    ✅ SUCCESS                              ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""
    echo "  Branch: ${WORKING_BRANCH}"
    echo "  PR:     ${PR_URL:-N/A}"
    echo ""
}

finalize_partial() {
    local reason="$1"
    
    log_phase "FINALIZING - PARTIAL"
    
    local commit_msg="wip: partial fix for issue #${ISSUE}"
    local commit_desc="${ISSUE_TITLE}

[...]

${reason}

Automatically generated by issue-resolver bot."

    if commit_changes "$commit_msg" "$commit_desc"; then
        push_branch
        
        if $TESTS_PASSED || git log --oneline "origin/${DEFAULT_BRANCH}..HEAD" | grep -q .; then
            create_pr
        fi
    else
        push_branch 2>/dev/null || true
    fi
    
    add_issue_comment "partial" "$reason"
    
    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║                 ⚠️  PARTIAL COMPLETION                     ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""
    echo "  Branch: ${WORKING_BRANCH}"
    echo "  Reason: ${reason}"
    echo ""
    echo "  Run again to continue:"
    echo "  ./resolve.py ${REPO} ${ISSUE}"
    echo ""
}

finalize_error() {
    local error_msg="$1"
    
    log_phase "FINALIZING - ERROR"
    
    if has_uncommitted_changes; then
        commit_changes "wip: attempted fix for issue #${ISSUE} (error)" "Error occurred: ${error_msg}" || true
        push_branch 2>/dev/null || true
    fi
    
    add_issue_comment "error" "$error_msg"
    
    echo ""
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║                    ❌ ERROR                                ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo ""
    echo "  ${error_msg}"
    echo ""
}
