#!/usr/bin/env bash
# lib/github.sh - GitHub operations

# Requires: GITHUB_TOKEN, REPO, ISSUE, WORK_DIR, BRANCH (optional)
# Exports: ISSUE_TITLE, ISSUE_BODY, ISSUE_LABELS, ISSUE_COMMENTS
#          DEFAULT_BRANCH, WORKING_BRANCH, RESUMING

setup_github_auth() {
    log "Setting up GitHub authentication..."
    if gh auth login --with-token <<< "${GITHUB_TOKEN}" 2>&1 | grep -q "error"; then
        log_error "GitHub authentication failed"
        return 1
    fi
    if gh auth status &>/dev/null; then
        log_success "GitHub authenticated"
        return 0
    else
        log_error "GitHub authentication verification failed"
        return 1
    fi
}

fetch_issue() {
    log "Fetching issue #${ISSUE} from ${REPO}..."
    
    local issue_json
    issue_json=$(gh issue view "$ISSUE" --repo "$REPO" --json title,body,labels,comments)
    
    ISSUE_TITLE=$(echo "$issue_json" | jq -r '.title')
    ISSUE_BODY=$(echo "$issue_json" | jq -r '.body // "No description provided."')
    ISSUE_LABELS=$(echo "$issue_json" | jq -r '.labels[].name' | tr '\n' ', ' | sed 's/,$//')
    ISSUE_COMMENTS=$(echo "$issue_json" | jq -r '.comments[].body' | head -c 2000)
    
    cat > /workspace/issue_context.md <<EOF
# Issue #${ISSUE}: ${ISSUE_TITLE}

## Labels
${ISSUE_LABELS:-None}

## Description
${ISSUE_BODY}

## Comments
${ISSUE_COMMENTS:-No comments}
EOF

    log_success "Issue fetched: ${ISSUE_TITLE}"
}

check_existing_branch() {
    local branch_name="${BRANCH:-fix/issue-${ISSUE}}"
    
    log "Checking for existing branch: ${branch_name}..."
    
    if git ls-remote --heads origin "$branch_name" 2>/dev/null | grep -q "$branch_name"; then
        log_success "Found existing branch on remote"
        return 0
    fi
    
    log "No existing branch found"
    return 1
}

clone_or_continue_repo() {
    log "Setting up repository ${REPO}..."
    
    local branch_name="${BRANCH:-fix/issue-${ISSUE}}"
    
    [[ -d "$WORK_DIR" ]] && rm -rf "$WORK_DIR"
    
    git clone --depth 100 "https://x-access-token:${GITHUB_TOKEN}@github.com/${REPO}.git" "$WORK_DIR" 2>/dev/null
    
    cd "$WORK_DIR"
    git config user.email "${GIT_AUTHOR_EMAIL:-bot@issue-resolver.local}"
    git config user.name "${GIT_AUTHOR_NAME:-Issue Resolver Bot}"
    
    DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
    
    if check_existing_branch; then
        log "Continuing on existing branch: ${branch_name}"
        git fetch origin "$branch_name"
        git checkout -b "$branch_name" "origin/$branch_name"
        WORKING_BRANCH="$branch_name"
        RESUMING=true
        log_success "Checked out existing branch with $(git log --oneline origin/${DEFAULT_BRANCH}..HEAD | wc -l) commit(s) ahead"
    else
        log "Creating new branch: ${branch_name}"
        git checkout -b "$branch_name"
        WORKING_BRANCH="$branch_name"
        RESUMING=false
        log_success "Created new branch"
    fi
    
    log_success "Repository ready (default branch: ${DEFAULT_BRANCH})"
}

has_uncommitted_changes() {
    cd "$WORK_DIR"
    ! git diff --quiet || ! git diff --staged --quiet
}

commit_changes() {
    local message="${1:-fix: resolve issue #${ISSUE}}"
    local description="${2:-}"
    
    log "Committing changes..."
    
    cd "$WORK_DIR"
    
    if ! has_uncommitted_changes; then
        log_warn "No changes to commit"
        return 1
    fi
    
    git add -A
    
    if [[ -n "$description" ]]; then
        git commit -m "$message" -m "$description"
    else
        git commit -m "$message"
    fi
    
    log_success "Changes committed"
    return 0
}

push_branch() {
    log "Pushing branch to remote..."
    
    cd "$WORK_DIR"
    git push -u origin "$WORKING_BRANCH" 2>/dev/null
    
    log_success "Branch pushed: ${WORKING_BRANCH}"
}

create_pr() {
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_warn "Dry run - skipping PR creation"
        return 0
    fi
    
    log "Creating pull request..."
    
    cd "$WORK_DIR"
    
    local existing_pr
    existing_pr=$(gh pr list --repo "$REPO" --head "$WORKING_BRANCH" --json number --jq '.[0].number' 2>/dev/null || echo "")
    
    if [[ -n "$existing_pr" ]]; then
        log_success "PR already exists: #${existing_pr}"
        PR_URL="https://github.com/${REPO}/pull/${existing_pr}"
        return 0
    fi
    
    PR_URL=$(gh pr create \
        --repo "$REPO" \
        --title "fix: ${ISSUE_TITLE}" \
        --body "## Summary
Automatically generated fix for #${ISSUE}

## Issue
${ISSUE_TITLE}

## Status
- Tests: $(if $TESTS_PASSED; then echo "✅ Passing"; else echo "❌ Failing"; fi)
- Review: $(if $REVIEW_PASSED; then echo "✅ Passed"; else echo "⚠️ Needs attention"; fi)

---
*Generated by issue-resolver*

Closes #${ISSUE}" \
        --base "$DEFAULT_BRANCH" \
        --head "$WORKING_BRANCH")
    
    log_success "Pull request created: ${PR_URL}"
}

add_issue_comment() {
    local status="$1"
    local details="${2:-}"
    
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        log_warn "Dry run - skipping issue comment"
        return 0
    fi
    
    log "Adding comment to issue #${ISSUE}..."
    
    local comment_body
    
    case "$status" in
        success)
            comment_body="## 🤖 Automated Fix Ready

A pull request has been created to resolve this issue.

**Branch:** \`${WORKING_BRANCH}\`
**PR:** ${PR_URL:-N/A}

### Status
- ✅ Implementation complete
- ✅ Tests passing
- ✅ Review passed

Please review the PR and merge if satisfactory."
            ;;
        partial)
            comment_body="## 🤖 Automated Fix - Partial Progress

I've made progress on this issue but couldn't complete it fully.

**Branch:** \`${WORKING_BRANCH}\`
**PR:** ${PR_URL:-Not created}

### Status
- ✅ Implementation attempted
- $(if $TESTS_PASSED; then echo "✅ Tests passing"; else echo "❌ Tests failing"; fi)
- $(if $REVIEW_PASSED; then echo "✅ Review passed"; else echo "⚠️ Review found issues"; fi)

### Details
${details}

### Next Steps
You can continue working on this branch manually, or run the resolver again:
\`\`\`bash
./resolve.py ${REPO} ${ISSUE} --branch ${WORKING_BRANCH}
\`\`\`"
            ;;
        error)
            comment_body="## 🤖 Automated Fix - Error

I encountered an error while trying to resolve this issue.

**Branch:** \`${WORKING_BRANCH}\`

### Error Details
${details}

### Next Steps
You can try running the resolver again or work on the branch manually:
\`\`\`bash
./resolve.py ${REPO} ${ISSUE} --branch ${WORKING_BRANCH}
\`\`\`"
            ;;
    esac
    
    gh issue comment "$ISSUE" --repo "$REPO" --body "$comment_body"
    
    log_success "Comment added to issue"
}
