'''Finalize partial step.'''

from __future__ import annotations

from ..step import AbstractStep
from ....lib.context import WorkflowContext
from ....lib.exceptions import StepExecutionError
from ..github.push_step import GithubPushStep
from ..github.create_pr_step import GithubCreatePRStep
from ..github.comment_step import GithubCommentStep
from .commit_step import CommitStep


class FinalizePartialStep(AbstractStep):
    '''Finalize workflow with partial status.'''

    def __init__(self, reason: str) -> None:
        super().__init__(name='Finalize Partial', retries=0)
        self.reason = reason

    def run(self, ctx: WorkflowContext) -> None:
        ctx.logger.phase('FINALIZING - PARTIAL')

        if ctx.config.issue is None or not ctx.issue_title:
            raise StepExecutionError('Issue metadata is missing for partial finalization.')

        commit_desc = (
            f'{ctx.issue_title}\n\n'
            '[...]\n\n'
            f'{self.reason}\n\n'
            'Automatically generated by issue-resolver bot.'
        )
        committed = False
        if ctx.git_service and ctx.git_service.has_changes():
            try:
                CommitStep(
                    message=f'wip: partial fix for issue #{ctx.config.issue}',
                    description=commit_desc,
                ).run(ctx)
                committed = True
            except StepExecutionError:
                committed = False

        if committed:
            GithubPushStep().run(ctx)
            if ctx.tests_passed or self._has_commits_ahead(ctx):
                GithubCreatePRStep().run(ctx)
        else:
            try:
                GithubPushStep().run(ctx)
            except StepExecutionError:
                ctx.logger.verbose('Failed to push branch after no commit')

        GithubCommentStep('partial', self.reason).run(ctx)
        self._print_banner(ctx)

    def _has_commits_ahead(self, ctx: WorkflowContext) -> bool:
        if ctx.git_service is None or not ctx.default_branch:
            return False
        try:
            return ctx.git_service.commits_ahead(ctx.default_branch) > 0
        except Exception:
            return False

    def _print_banner(self, ctx: WorkflowContext) -> None:
        ctx.logger.banner('⚠️  PARTIAL COMPLETION')
        ctx.logger.log(f'  Branch: {ctx.working_branch}')
        ctx.logger.log(f'  Reason: {self.reason}')
        ctx.logger.log('')
        ctx.logger.log('  Run again to continue:')
        ctx.logger.log(f'  ./resolve.py {ctx.config.repo} {ctx.config.issue}')
