'''Finalize success step.'''

from __future__ import annotations

from ..step import AbstractStep
from ....lib.context import WorkflowContext
from ....lib.exceptions import StepExecutionError
from ..github.push_step import GithubPushStep
from ..github.create_pr_step import GithubCreatePRStep
from ..github.comment_step import GithubCommentStep
from .commit_step import CommitStep


class FinalizeSuccessStep(AbstractStep):
    '''Finalize workflow with success status.'''

    def __init__(self, defer_report: bool = False) -> None:
        super().__init__(name='Finalize Success', retries=0)
        self.defer_report = defer_report

    def run(self, ctx: WorkflowContext) -> None:
        ctx.logger.phase('FINALIZING - SUCCESS')

        if ctx.config.issue is None or not ctx.issue_title:
            raise StepExecutionError('Issue metadata is missing for success finalization.')

        CommitStep(
            message=f'fix: resolve issue #{ctx.config.issue}',
            description=f'{ctx.issue_title}\n\nAutomatically generated by issue-resolver bot.',
        ).run(ctx)

        GithubPushStep().run(ctx)
        GithubCreatePRStep().run(ctx)

        if not self.defer_report:
            GithubCommentStep('success').run(ctx)
            self._print_banner(ctx)

    def _print_banner(self, ctx: WorkflowContext) -> None:
        ctx.logger.banner('✅ SUCCESS')
        ctx.logger.log(f'  Branch: {ctx.working_branch}')
        ctx.logger.log(f'  PR:     {ctx.pr_url or "N/A"}')
        if ctx.suggested_issue_urls:
            ctx.logger.log('  Suggestions:')
            for url in ctx.suggested_issue_urls:
                ctx.logger.log(f'   - {url}')
