'''Review workflow implementation.'''

from __future__ import annotations

from datetime import datetime

from ..lib.context import WorkflowContext
from ..lib.exceptions import StepExecutionError
from .workflow import AbstractWorkflow
from .steps import (
    CleanupStateStep,
    CommitStep,
    CreateIssueContextStep,
    FinalizeErrorStep,
    GithubCloneRepoStep,
    GithubLoginStep,
    GithubPushStep,
    ReportAggregationStep,
    ReportPhaseStep,
)
from .steps.step import AbstractStep


class ReviewWorkflow(AbstractWorkflow):
    '''Workflow to generate review reports for a repository.'''

    def __init__(self) -> None:
        super().__init__('Review Workflow')

    def build_steps(self, ctx: WorkflowContext) -> list[AbstractStep]:
        steps: list[AbstractStep] = [
            GithubLoginStep(),
            GithubCloneRepoStep(),
        ]

        steps.append(CreateIssueContextStep('review'))

        steps.extend(
            [
                ReportPhaseStep('security-report', 'Security Report'),
                ReportPhaseStep('architecture-report', 'Architecture Report'),
                ReportPhaseStep('customer-report', 'Customer Report'),
                ReportPhaseStep('engineering-report', 'Engineering Report'),
                ReportPhaseStep('testing-report', 'Testing Report'),
                ReportPhaseStep('resource-report', 'Resource Report'),
                CleanupStateStep(),
                ReportAggregationStep(),
            ]
        )
        return steps

    def run(self, ctx: WorkflowContext) -> bool:
        ctx.logger.banner(f'Workflow: {self.name}')

        for step in self.build_steps(ctx):
            try:
                step.execute(ctx)
            except StepExecutionError as error:
                FinalizeErrorStep(str(error)).run(ctx)
                return False
            except Exception as error:
                FinalizeErrorStep(str(error)).run(ctx)
                return False

        self._finalize(ctx)
        return True

    def _finalize(self, ctx: WorkflowContext) -> None:
        ctx.logger.phase('FINALIZING - SUCCESS')
        report_date = datetime.utcnow().strftime('%Y-%m-%d')
        CommitStep(
            message='chore: add review report',
            description='\n\nAutomatically generated by issue-resolver bot.',
        ).run(ctx)
        GithubPushStep().run(ctx)
        self._create_review_pr(ctx, report_date)

        if ctx.config.issue is not None and not ctx.config.dry_run:
            try:
                from .steps.github.comment_step import GithubCommentStep

                GithubCommentStep('success').run(ctx)
            except Exception:
                ctx.logger.warn('Failed to post success comment')

        ctx.logger.banner('✅ REVIEW COMPLETE')
        ctx.logger.log(f'  Repository: {ctx.config.repo}')
        ctx.logger.log(f'  PR:         {ctx.pr_url or "N/A"}')

    def _create_review_pr(self, ctx: WorkflowContext, report_date: str) -> None:
        if ctx.config.dry_run:
            ctx.logger.warn('Dry run - skipping PR creation')
            return

        if ctx.github is None:
            raise StepExecutionError('GitHub service is not available on context.')
        if not ctx.working_branch or not ctx.default_branch:
            raise StepExecutionError('Branch information is missing.')

        ctx.logger.log('Creating pull request...')
        try:
            existing_pr = ctx.github.find_pr_for_branch(ctx.working_branch)
        except Exception as exc:
            raise StepExecutionError('Failed to check for existing PR.') from exc

        if existing_pr:
            ctx.pr_url = f'https://github.com/{ctx.config.repo}/pull/{existing_pr}'
            ctx.logger.success(f'PR already exists: #{existing_pr}')
            return

        title = f'📊 Code Review Report - {report_date}'
        body = (
            '## Automated Code Review Report\n'
            f'**Report Date:** {report_date}\n'
            '**Report File:** `/reports/<date>.md`\n\n'
            '### Summary\n'
            'This PR contains an automated code review report generated by the review workflow.\n\n'
            '---\n\n'
            '*Generated by review-reporter*'
        )

        try:
            ctx.pr_url = ctx.github.create_pull_request(
                title=title,
                body=body,
                head=ctx.working_branch,
                base=ctx.default_branch,
            )
        except Exception as exc:
            raise StepExecutionError('Failed to create pull request.') from exc

        ctx.logger.success(f'Pull request created: {ctx.pr_url}')
