'''GitHub pull request creation step.'''

from __future__ import annotations

from ..step import AbstractStep
from ....lib.context import WorkflowContext
from ....lib.exceptions import StepExecutionError


class GithubCreatePRStep(AbstractStep):
    '''Create pull request for the working branch.'''

    def __init__(self) -> None:
        super().__init__(name='Create Pull Request', retries=0)

    def run(self, ctx: WorkflowContext) -> None:
        if ctx.github is None:
            raise StepExecutionError('GitHub service is not available on context.')
        if not ctx.working_branch or not ctx.default_branch:
            raise StepExecutionError('Branch information is missing.')

        if ctx.config.dry_run:
            ctx.logger.log(
                f'[DRY RUN] Would create PR for branch: {ctx.working_branch}'
            )
            return

        ctx.logger.log('Creating pull request...')
        try:
            existing_pr = ctx.github.find_pr_for_branch(ctx.working_branch)
        except Exception as exc:
            raise StepExecutionError('Failed to check for existing PR.') from exc

        if existing_pr:
            ctx.pr_url = f'https://github.com/{ctx.config.repo}/pull/{existing_pr}'
            ctx.logger.success(f'PR already exists: #{existing_pr}')
            return

        if not ctx.issue_title:
            raise StepExecutionError('Issue title is not available for PR creation.')

        tests_status = '✅ Passing' if ctx.tests_passed else '❌ Failing'
        review_status = '✅ Passed' if ctx.review_passed else '⚠️ Needs attention'
        body = (
            '## Summary\n'
            f'Automatically generated fix for #{ctx.config.issue}\n\n'
            '## Issue\n'
            f'{ctx.issue_title}\n\n'
            '## Status\n'
            f'- Tests: {tests_status}\n'
            f'- Review: {review_status}\n\n'
            '---\n'
            '*Generated by issue-resolver*\n\n'
            f'Closes #{ctx.config.issue}'
        )

        try:
            ctx.pr_url = ctx.github.create_pull_request(
                title=f'fix: {ctx.issue_title}',
                body=body,
                head=ctx.working_branch,
                base=ctx.default_branch,
            )
        except Exception as exc:
            raise StepExecutionError('Failed to create pull request.') from exc

        ctx.logger.success(f'Pull request created: {ctx.pr_url}')
